name: Build and Push to GCP

on:
  push:
    branches: ["**"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
	  token_format: 'access_token'
	  workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      # Authenticates Docker directly without needing the full gcloud SDK
      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # Using the build-push action enables automatic GitHub Actions caching
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            us-central1-docker.pkg.dev/cssfinder-gilbert/cssfinder-gilbert-repo/flask-app:${{ github.sha }}
            us-central1-docker.pkg.dev/cssfinder-gilbert/cssfinder-gilbert-repo/flask-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cssfinder
          region: us-central1
          image: us-central1-docker.pkg.dev/cssfinder-gilbert/cssfinder-gilbert-repo/flask-app:${{ github.sha }}
          flags: '--allow-unauthenticated'
